manifests/00_clusteropenshiftapiserveroperator_00_namespace.yaml, manifests/00_clusteropenshiftapiserveroperator_01_config.crd.yaml, manifests/00_clusteropenshiftapiserveroperator_02_config.yaml, manifests/00_clusteropenshiftapiserveroperator_03_configmap.yaml, manifests/00_clusteropenshiftapiserveroperator_04_roles.yaml, manifests/00_clusteropenshiftapiserveroperator_05_serviceaccount.yaml, manifests/00_clusteropenshiftapiserveroperator_06_deployment.yaml
=> fix whitespace

pkg/operator/operator.go
This is a simple way to prevent hotlooping since we watch so many resources.  We also want the openshiftapiserver to generally be available, so handling a burst of 4 changes followed by 3 changes per minute after that seems reasonable.
/assign @sttts @mfojtik
=> prevent hotlooping in operator

bindata/v3.11.0/openshift-apiserver/ds.yaml, manifests/0000_20_cluster-openshift-apiserver-operator_06_deployment.yaml, pkg/operator/v311_00_assets/bindata.go
/assign @abhinavdahiya @mfojtik
=> tolerate any taint

glide.lock, vendor/github.com/openshift/api/authorization/OWNERS, vendor/github.com/openshift/api/oauth/OWNERS, vendor/github.com/openshift/api/security/OWNERS, vendor/github.com/openshift/api/user/OWNERS, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
=> fix apiservice registration update

pkg/operator/sync_openshiftapiserver_v311_00.go
=> stop managing the network apis

manifests/0000_20_cluster-openshift-apiserver-operator_06_deployment.yaml, manifests/image-references
cc @deads2k @mfojtik @smarterclayton
=> add image-references

pkg/operator/observe_config.go, pkg/operator/operator.go, pkg/operator/starter.go
Reads etcd endpoint information for storage.
/assign @mfojtik
=> read etcd endpoint information

pkg/operator/observe_config.go
Also fixes a constant update problem.  Tested on local cluster.
=> use proper set nested function

manifests/0000_20_cluster-openshift-apiserver-operator_06_deployment.yaml, manifests/image-references
=> fix deployment env

README.md
@derekwaynecarr per request
@sttts @mfojtik @ironcladlou this is what I do.
=> simple development flow

glide.lock, pkg/operator/starter.go, vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go, vendor/github.com/openshift/api/operator/v1alpha1/types.go, vendor/github.com/openshift/api/operator/v1alpha1/types_swagger_doc_generated.go, vendor/github.com/openshift/library-go/.travis.yml, vendor/github.com/openshift/library-go/glide.lock, vendor/github.com/openshift/library-go/hack/verify-golint.sh, vendor/github.com/openshift/library-go/pkg/config/configdefaults/config_default.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/storage.go, vendor/github.com/openshift/library-go/pkg/operator/status/controller.go, vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helpers.go
uses the same library-go logic as controller-manager
=>  add ClusterOperator status

glide.lock, pkg/operator/observe_config.go, pkg/operator/observe_config_test.go, pkg/operator/operator.go, pkg/operator/starter.go, vendor/github.com/openshift/api/config/v1/register.go, vendor/github.com/openshift/client-go/glide.lock, vendor/github.com/pkg/profile/.travis.yml
~~Depends on https://github.com/openshift/cluster-openshift-apiserver-operator/pull/40~~
cc @deads2k
=> Observe internalregistry hostname

pkg/operator/configobservation/etcd/observe_etcd.go
temporarily, until the etcd service is updated
[WIP] until pull https://github.com/openshift/installer/pull/694 is merged.
=> use host-etcd service

bindata/v3.11.0/openshift-apiserver/ds.yaml, pkg/operator/v311_00_assets/bindata.go
/cc @deads2k 
/cc @aveshagarwal
=> make daemonset pods node critical priority

pkg/operator/detectinputchange/as_configmap.go, pkg/operator/workload_controller_openshiftapiserver_v311_00.go
This watches for changes to a configmap and can cause a rollout of the deployment
/assign @mfojtik @sttts
=> force rollout on input change managed by a different controller

manifests/0000_20_cluster-openshift-apiserver-operator_08_clusteroperator.yaml
Adding this resource should give the CVO visibility into whether our component is working or not.
/assign @sttts
=> add clusteroperator resource to CVO payload

manifests/0000_20_cluster-openshift-apiserver-operator_00_namespace.yaml, manifests/0000_20_cluster-openshift-apiserver-operator_06_service.yaml, manifests/0000_90_cluster-openshift-apiserver-operator_01_prometheusrole.yaml, manifests/0000_90_cluster-openshift-apiserver-operator_02_prometheusrolebinding.yaml, manifests/0000_90_cluster-openshift-apiserver-operator_03_servicemonitor.yaml
=> add service monitor resources for operator

manifests/0000_20_openshift-apiserver-operator_08_clusteroperator.yaml
wait for this to pass a few times
/test e2e-aws
=> add cluster operator to payload

pkg/operator/workload_controller.go
If we wait for the kube-apiserver to be available via cluster operator status, then we are assured that it has written out the authentication ca bundle configmap.  We can't really do anything without a ready kube-apiserver, so this should be zero impact.
@smarterclayton @sttts I really should have thought of this first.
/assign @sttts
=> wait for kubeapiserver to be ready

manifests/0000_20_openshift-apiserver-operator_07_deployment.yaml
=> explicitly list metrics port as first containerPort

bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml, bindata/v3.11.0/openshift-apiserver/ds.yaml, pkg/operator/resourcesynccontroller/resourcesynccontroller.go, pkg/operator/v311_00_assets/bindata.go, pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
This completes the wiring of explicit ca bundles.
=> set the explicit ca bundles

pkg/operator/configobservation/ingresses/observe_ingresses.go, pkg/version/version.go
@ironcladlou this add event so when bad things start to happen in your observer we can see them...
=> ingress: add event to ingress observer when domain change

bindata/v3.11.0/openshift-apiserver/ds.yaml, manifests/0000_61_openshift-apiserver-operator_07_deployment.yaml, pkg/operator/v311_00_assets/bindata.go
@smarterclayton @deads2k @derekwaynecarr
=> set cpu request for pod and operator

pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
See the comment in the diff.
/assign @bparees @mfojtik
=> ensure we rollout when image pull spec changes

bindata/v3.11.0/openshift-apiserver/ds.yaml, pkg/operator/v311_00_assets/bindata.go
=> Set openshift-apiserver privileged for audit to be able to write to /var/log/openshift-apiserver

pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
In order to assist with problem determination, report why a rollout was forced by emitting an event with the reason.
=> when forcing a rolling update, emit event with reason

pkg/cmd/operator/cmd.go
=> cmd: fix operator component name

bindata/v3.11.0/openshift-apiserver/ds.yaml, pkg/operator/v311_00_assets/bindata.go, pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
=> Set audit directory to be 0700

manifests/0000_61_openshift-apiserver-operator_03_version-mapping.yaml, manifests/0000_61_openshift-apiserver-operator_07_deployment.yaml, manifests/0000_61_openshift-apiserver-operator_08_clusteroperator.yaml
https://github.com/openshift/cluster-kube-apiserver-operator/pull/308
=> minor fitting to set versions for our operator

glide.lock, pkg/operator/resourcesynccontroller/resourcesynccontroller.go, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go, vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go, vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go, vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
Depends on https://github.com/openshift/library-go/pull/321
Adds call to handler function to serve resource controller sync rules
=> Debug handler

bindata/v3.11.0/openshift-apiserver/ds.yaml, manifests/0000_61_openshift-apiserver-operator_07_deployment.yaml, pkg/operator/v311_00_assets/bindata.go
Just an oversight in our definitions
=> report failures to pod status

.travis.yml
/assign @tnozicka @sttts
Requires https://github.com/openshift/release/pull/3488
=> Switch openshift/oas-o to go1.11

Dockerfile, Dockerfile.rhel7
=> Switch to go1.11

pkg/operator/operatorclient/interfaces.go, pkg/operator/resourcesynccontroller/resourcesynccontroller.go, pkg/operator/starter.go, pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
etcd info is no longer in kube-system
=> switch to pull etcd info from openshift-config

glide.lock, vendor/github.com/openshift/api/config/v1/types_feature.go, vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
saves one minute during upgrade
=> shorten leader election

bindata/v3.11.0/openshift-apiserver/ns.yaml, pkg/operator/v311_00_assets/bindata.go
/cc @sttts @deads2k @brancz @paulfantom
=> bindata: monitor openshift-apiserver namespace

bindata/v3.11.0/openshift-apiserver/ds.yaml, manifests/0000_30_openshift-apiserver-operator_07_deployment.yaml, manifests/image-references, pkg/operator/v311_00_assets/bindata.go
fix bug in https://github.com/openshift/cluster-openshift-apiserver-operator/pull/213
=> Use the new "openshift-apiserver" image

glide.lock, vendor/github.com/evanphx/json-patch/patch.go, vendor/github.com/evanphx/json-patch/patch_test.go, vendor/github.com/openshift/api/config/v1/types_dns.go, vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go, vendor/github.com/openshift/library-go/alpha-build-machinery/Makefile, vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.example.mk, vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.example.mk.help.log, vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.mk, vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/Makefile, vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/Makefile.test, vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/Makefile.test.log, vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/ocp.spec, vendor/github.com/openshift/library-go/alpha-build-machinery/make/operator.example.mk, vendor/github.com/openshift/library-go/alpha-build-machinery/make/operator.example.mk.help.log, vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/images.mk, vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/rpm.mk, vendor/github.com/openshift/library-go/pkg/assets/create/create_test.go, vendor/github.com/openshift/library-go/pkg/assets/create/creater.go, vendor/github.com/openshift/library-go/pkg/assets/create/testdata/operator-config-empty-status.yaml, vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider_test.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy_test.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go, vendor/google.golang.org/appengine/capability/capability.go, vendor/k8s.io/component-base/Godeps/Godeps.json
includes https://github.com/openshift/library-go/pull/499 fix
cc @sttts
=> bump to fix proxy observation

pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
=> Sort the EnvVar from Proxy string map

pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
Rework the log level handling as the entrypoint is now wrapped by bash.
=> Bug 1746942: Fix setting the log level

pkg/operator/prunecontroller/prune_controller.go
The key secret have a finalizer. This must be removed before deletion.
=> encryption: remove key secret finalizer before pruning

pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
This patch makes the default image registry self signed certificates available to OpenShift API Server pods.
=> Bug 1716835: Hooking Image Registry internal service certificates

glide.lock, pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go, vendor/github.com/openshift/api/apps/v1/generated.proto, vendor/github.com/openshift/api/apps/v1/types.go, vendor/github.com/openshift/api/authorization/v1/generated.proto, vendor/github.com/openshift/api/authorization/v1/types.go, vendor/github.com/openshift/api/authorization/v1/zz_generated.swagger_doc_generated.go, vendor/github.com/openshift/api/build/v1/generated.proto, vendor/github.com/openshift/api/build/v1/types.go, vendor/github.com/openshift/api/route/v1/generated.proto, vendor/github.com/openshift/api/route/v1/types.go, vendor/github.com/openshift/api/template/v1/generated.proto, vendor/github.com/openshift/api/template/v1/types.go, vendor/github.com/openshift/library-go/pkg/authentication/bootstrapauthenticator/bootstrap.go, vendor/github.com/openshift/library-go/pkg/authentication/bootstrapauthenticator/bootstrap_test.go, vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
=> [release-4.3] Bug 1781577: Fix panic in workload controller

pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go, test/e2e/operator_test.go
=> merge hashing resources for forced DS rollouts

pkg/operator/starter.go
4.3 uses a daemonset to manage apiserver pods, so the 4.4 deployment is likely to cause trouble if not removed.
=> Bug 1805388: Cleanup 4.4 deployment on downgrade to 4.3

pkg/operator/dsnodeprovider.go
Backport of https://github.com/openshift/cluster-openshift-apiserver-operator/pull/311.
=> Bug 1837353: encryption: don't degrade when daemonset is not found

pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
Use apiserver node names, not pod names, when naming podnetworkconnectivitychecks.
=> connectivitycheckcontroller: check names should use node names

pkg/operator/starter.go
Counterpart to https://github.com/openshift/cluster-authentication-operator/pull/324.
The annotation `oauth-apiserver.openshift.io/secure-token-storage: true` set on the config/v1 apiserver object make openshift-apiserver deeply log oauth tokens, noth access and authorize (if openshift-apiserver is responsible for this; in fresh 4.6 install it is not, but oauth-apiserver is). 
This requires that there are no non-sha256 tokens in the system. For 4.6 installs this is guaranteed. 
After downgrade to 4.5 there is a controller removing the annotation. 
After upgrade from 4.5, the annotation is not set. The admin can set it manually after having made sure that no non-sha256 tokens exist.
For upgrade to 4.7, non-sha256 tokens must not exist. If they do, the upgrade will be blocked by the auth …
=> Bug 1878648: oauth-apiserver: audit log oauthaccesstokens if fresh 4.6 install

pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go, test/e2e/connectivity_check_test.go
This reverts commit bef7a2f3a54372e3fd52e56e2b4276fa4a045515.
=> Revert "connectivitycheckcontroller: disable by default"

manifests/0000_30_openshift-apiserver-operator_09_flowschema.yaml
This is matches openshift/enhancements#510 and doesn't change existing behavior
=> add current profile annotations to CVO manifests

OWNERS
=> Remove tnozicka and add soltysh to OWNERS

go.mod, go.sum, pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go, vendor/github.com/openshift/library-go/pkg/config/serving/server.go, vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go, vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go, vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go, vendor/modules.txt
=> Bug 1912820: competing connectivitycheckcontrollers cause pod restarts during upgrades

.ci-operator.yaml, Makefile
Pre-req for https://github.com/openshift/cluster-openshift-apiserver-operator/pull/448.
=> Bug 1953563: Add .ci-operator.yaml with build_root_image

.ci-operator.yaml, Makefile, go.mod, go.sum, vendor/github.com/openshift/build-machinery-go/Makefile, vendor/github.com/openshift/build-machinery-go/OWNERS, vendor/github.com/openshift/build-machinery-go/README.md, vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log, vendor/github.com/openshift/build-machinery-go/make/golang.example.mk.help.log, vendor/github.com/openshift/build-machinery-go/make/golang.mk, vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk, vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log, vendor/github.com/openshift/build-machinery-go/make/targets/golang/version.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk, vendor/modules.txt
Needs https://github.com/openshift/cluster-openshift-apiserver-operator/pull/452 and https://github.com/openshift/release/pull/18525.
=> Bug 1953563: Switch to Golang 1.16 for build-root

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/apiservice/apigroup.go, vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go, vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go, vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go, vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go, vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go, vendor/k8s.io/client-go/restmapper/category_expansion.go, vendor/k8s.io/client-go/restmapper/discovery.go, vendor/k8s.io/client-go/restmapper/shortcut.go, vendor/modules.txt
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1979303 and https://bugzilla.redhat.com/show_bug.cgi?id=1982398
=> Bug 1979303: clear encryption conditions when there is no work to be done

pkg/operator/starter.go
=> pkg/operator: set high inertia for all topologies except SingleReplica

bindata/v3.11.0/openshift-apiserver/svc.yaml, manifests/0000_90_openshift-apiserver-operator_04_servicemonitor-apiserver.yaml, manifests/0000_90_openshift-apiserver-operator_05_check-endpoints_service.yaml, manifests/0000_90_openshift-apiserver-operator_05_check-endpoints_servicemonitor.yaml, pkg/operator/v311_00_assets/bindata.go
- remove unnecessary annotations
=> update apiserver and check-endpoints service selectors

bindata/v3.11.0/config/defaultconfig.yaml, bindata/v3.11.0/openshift-apiserver/deploy.yaml, pkg/operator/v311_00_assets/bindata.go
=> [release 4.10] Bug 2109235: openshift-apiserver pods never going NotReady

pkg/operator/configobservation/configobservercontroller/observe_config_controller.go, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go, vendor/modules.txt
This will allow us to have techpreview fields for openshift APIs.
=> Plumb featuregates to the openshift-apiserver

test/e2e/operator_test.go
Previously, the test modified the `etcd-signer-ca` to see if a new re-deployment would be triggered. 
About two months ago, [the CEO introduced a change](https://github.com/openshift/cluster-etcd-operator/pull/1194) that runs a controller which overwrites (syncs) the secret from a different source.
This change broke the test, which has been failing for nearly [two months](https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-cluster-openshift-apiserver-operator-master-e2e-aws-operator?buildId=).
This PR changes the test to modify the operator's configuration, which is fully controlled by the operator, to trigger a re-deployment. This is what the test was originally supposed to check.
The `TestRedeployOnConfigChange` test was added in …
=> NO-ISSUE: fix: TestRedeployOnConfigChange

Dockerfile
test with https://github.com/openshift/api/pull/2030
=> create CRDs from openshift/api

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go, vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go, vendor/github.com/openshift/library-go/pkg/operator/v1helpers/canonicalize.go, vendor/modules.txt
proof of https://github.com/openshift/library-go/pull/1798
=> API-1835: last transition time update

go.mod, go.sum, pkg/operator/configobservation/configobservercontroller/observe_config_controller.go, pkg/operator/resourcesynccontroller/resourcesynccontroller.go, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go, vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/apiservice/apiservice_controller.go, vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/auditpolicy/auditpolicy_controller.go, vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/nsfinalizer/finalizer_controller.go, vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/workload/workload.go, vendor/github.com/openshift/library-go/pkg/operator/apiserver/controllerset/apiservercontrollerset.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go, vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go, vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go, vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go, vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go, vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go, vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go, vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go, vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go, vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go, vendor/github.com/openshift/library-go/pkg/operator/secretspruner/prune_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go, vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go, vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go, vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go, vendor/modules.txt
proof of https://github.com/openshift/library-go/pull/1794
=> API-1835: update for more apply loops
