openshift/cluster-openshift-apiserver-operator

Makefile

/assign @tnozicka 
The image is prefixed with origin and needs that prefix to work locally.

typo in image name

---

bindata/v3.11.0/openshift-apiserver/ds.yaml
pkg/operator/sync_openshiftapiserver_v311_00.go
pkg/operator/v311_00_assets/bindata.go

This prevents the initial creation of apiservices that won't work.
/assign @mfojtik

 don't manage apiservices until daemonset is up

---

manifests/0000_20_cluster-openshift-apiserver-operator_00_namespace.yaml
manifests/0000_20_cluster-openshift-apiserver-operator_03_configmap.yaml
manifests/0000_20_cluster-openshift-apiserver-operator_04_roles.yaml
manifests/0000_20_cluster-openshift-apiserver-operator_05_serviceaccount.yaml
manifests/0000_20_cluster-openshift-apiserver-operator_06_service.yaml
manifests/0000_20_cluster-openshift-apiserver-operator_07_deployment.yaml
pkg/operator/starter.go

Moves our namespace to openshift-cluster-openshift-apiserver-operator and updates our ClusterOperator to match.
/assign @sanchezl

move to operator specific namespace

---

pkg/operator/observe_config.go
pkg/operator/operator.go
pkg/operator/starter.go
pkg/operator/sync_openshiftapiserver_v311_00.go

This information actually originates in the kube-system (or etcd) namespace.
/assign @sanchezl

pick up correct source of etcd connection info

---

bindata/v3.11.0/openshift-apiserver/ds.yaml
pkg/operator/v311_00_assets/bindata.go

"crictl ps -a" does not show pod names. So during disaster recovery full names for the containers is helpful.

Use openshift-apiserver container name for easier debugging

---

README.md

https://github.com/openshift/cluster-openshift-apiserver-operator/pull/49 changed the operator's namespace from "openshift-core-operators" to "openshift-cluster-openshift-apiserver-operator" but did not update the README.

Update namespace in README.md

---

pkg/operator/configobservation/configobservercontroller/observe_config_controller.go

A temporary measure to eliminate flapping. Related to https://github.com/openshift/cluster-openshift-apiserver-operator/pull/69 and https://github.com/openshift/cluster-openshift-apiserver-operator/pull/64
/assign @bparees

remove flapping config observation

---

pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
pkg/operator/configobservation/ingresses/observe_ingresses.go
pkg/operator/configobservation/interfaces.go
pkg/operator/starter.go

* `pkg/operator/configobservation/configobservercontroller/observe_config_controller.go` (`NewConfigObserver`): Rename `imageConfigInformers` to `configInformers`, and use the same informer for both image configs and ingress configs.
Add `IngressConfigLister` and `IngressConfigSynced` to listers.
Add `ObserveIngressDomain` to observers.
Register event handler for ingresses.config.openshift.io.
* `pkg/operator/configobservation/ingresses/observe_ingresses.go` (`ObserveIngressDomain`): Add new observer to set `routingConfig.Subdomain` from the cluster ingress config.
* `pkg/operator/configobservation/interfaces.go` (`Listers`): Add `IngressConfigLister` and `IngressConfigSynced`.
* `pkg/operator/starter.go` (`RunOperator`): Rename `imageConfigInformers` to `configInformers`.
Related to …

Configure routing subdomain

---

bindata/v3.11.0/openshift-apiserver/ds.yaml
manifests/0000_20_cluster-openshift-apiserver-operator_07_deployment.yaml
pkg/operator/v311_00_assets/bindata.go

One in a series of PRs to set memory requests for all control plane and high memory use components.
We are encountering master instability (https://github.com/openshift/installer/pull/408 https://github.com/openshift/installer/pull/785) as the number of components increase because many components run `BestEffort` giving the scheduler no information on pod resource usage.
On a steady state empty cluster, `openshift-apiserver` uses 179Mi.
{pod_name="apiserver-t5v2d"} | 179249152
Because it is a control plane component, I'm giving it a buffer and setting to `200Mi`
@deads2k @sttts  @derekwaynecarr

add memory request to openshift-apiserver and operator pods

---

manifests/0000_20_cluster-openshift-apiserver-operator_08_clusteroperator.yaml

This reverts commit a07dc5caaa4bdb13513a28bb2382464520580ab1.
For more info https://github.com/openshift/cluster-kube-apiserver-operator/pull/167
/cc @deads2k

Revert "add clusteroperator resource to CVO payload"

---

bindata/v3.11.0/openshift-apiserver/ds.yaml
pkg/operator/starter.go
pkg/operator/v311_00_assets/bindata.go
pkg/operator/workload_controller.go
pkg/operator/workload_controller_openshiftapiserver_v311_00.go

1) watch the image.config.openshift.io and the configmap it references as a source of additional CAs to trust for image import.
2) sync that configmap into the openshift-apiserver namespace and mount the configmap into the apiserver pod.  CAs will be consumed by the imageimport logic inside the apiserver (work to be done in origin).

copy cluster image CAs to api server configmap

---

pkg/operator/workload_controller_openshiftapiserver_v311_00.go

The progressing check is wrong
Fixes #86 
/assign @mfojtik @sanchezl 
@sanchezl please write a unit test and verify

fix the progressing check

---

bindata/v3.11.0/openshift-apiserver/ds.yaml
pkg/operator/v311_00_assets/bindata.go

The apiserver waits up to 60 seconds for pending non-long-running requests to finish. We should wait as least as long for graceful termination to finally terminate the pod with SIGKILL.

Set terminationGracePeriodSeconds for enough graceful termination time

---

pkg/operator/finalizer_controller.go
pkg/operator/starter.go

this allows us to delete the openshift-apiserver namespace.
When running an aggregated API on the platform, you delete the namespace hosting the aggregated API.  Doing that the namespace controller starts by doing complete discovery and then deleting all objects, but pods have a grace period, so it deletes the rest and requeues.  The ns controller starts again and does a complete discovery and.... fails.  The failure means it refuses to complete the cleanup.  Now, we don't *actually* want to delete the resoruces from our aggregated API, only the server plus config
if we remove the apiservices to unstick it, GC will start cleaning everything.  For now, we can unbork 4.0, but clearing the finalizer after the pod and daemonset we created are gone.
/assign @mfojtik @sttts

force clear the kube finalizer when kube resources are gone

---

pkg/operator/workload_controller.go

need to watch the workload resource we create
/assign @sanchezl

watch daemonsets, not deployments

---

pkg/operator/starter.go
pkg/operator/workloadcontroller/apigroup.go
pkg/operator/workloadcontroller/workload_controller.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go

Long ago, past me hit a problem in the aggregator that I suspected was openapi taking a long time.  We would transition an apiservice to available, but the proxy wasn't ready.  This does an actual check against the kube-apiserver to wait for them all to respond.
ref https://github.com/openshift/origin/blob/release-3.11/pkg/oc/clusteradd/componentinstall/readiness_apigroup.go

 add a check that actually attempts to hit the openshift api discovery

---

pkg/operator/starter.go
pkg/operator/workloadcontroller/apigroup.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go

Add APIServices as related so that must-gather will pick them up for us and the webconsole can know we care about them too.
@eparis 
@juanvallejo

add related apiservices

---

pkg/operator/configobservation/ingresses/observe_ingresses.go

* `pkg/operator/configobservation/ingresses/observe_ingresses.go` (`ObserveIngressDomain`): Fix the name of the config object in a log message.

Fix log message in the ingress config observer

---

bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
bindata/v3.11.0/openshift-apiserver/ds.yaml
pkg/operator/v311_00_assets/bindata.go

... to be on by default and log to /var/log/openshift-apiserver on the host, in analogy to kube-apiserver.
Prerequisite: https://github.com/openshift/origin/pull/21831

Configure auditing

---

manifests/0000_61_openshift-apiserver-operator_03_version-mapping.yaml
manifests/0000_61_openshift-apiserver-operator_07_deployment.yaml
pkg/operator/starter.go
pkg/operator/workloadcontroller/workload_controller.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go

This updates our operator to correctly report operand and operator versions in clusteroperator.status. It does this by relying the substitution value (@smarterclayton you're going to catch me on that right?) and (in the case of library-go), the watchable, thread-safe version application logic.
It also relies of the clever use of CVO merge logic (I think) to avoid overwriting all configmap keys so that I effectively keep a history of all the levels I've installed in the past.
@smarterclayton @bparees @ironcladlou 
@openshift/sig-master

update to manage versions correctly

---

pkg/operator/workloadcontroller/workload_controller.go

When the management state value is set to `foo`, we should stop managing and additionally emit a warning. We don't want to emit a warning per controller loop, so I added one to target config reconciler in each operator.

targetconfigcontroller: emit warning when management state is set to unknown value

---

pkg/cmd/resourcegraph/resourcegraph.go
pkg/operator/configobservation/project/observe_projects.go
pkg/operator/configobservation/project/observe_projects_test.go
pkg/operator/operatorclient/interfaces.go
pkg/operator/resourcesynccontroller/resourcesynccontroller.go
pkg/operator/starter.go
pkg/operator/workloadcontroller/workload_controller.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1673155
The openshift-apiserver accepts a namspace/name format, but our operator managed config doesn't have that flexibility.  Force the namespace during config observation to bridge the gap.
/assign @mfojtik @soltysh

set project template reference namespace

---

glide.lock
pkg/operator/finalizer_controller.go
pkg/operator/workloadcontroller/workload_controller.go
vendor/github.com/openshift/api/config/v1/types_console.go
vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
vendor/github.com/openshift/library-go/Makefile
vendor/github.com/openshift/library-go/cmd/crd-schema-gen/generator/generator.go
vendor/github.com/openshift/library-go/cmd/crd-schema-gen/main.go
vendor/github.com/openshift/library-go/glide.lock
vendor/github.com/openshift/library-go/glide.yaml
vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go

we introduced these when we had stability concerns.  We can remove them to gain some performance and chase down any rogue actors.
we agreed in slack already.

remove artificial rate limits

---

pkg/operator/starter.go

I believe proto client is safe for api registration client and informer. The JSON client showed up in prometheus metrics and this is low hanging fruit.
/cc @deads2k

operator: use proto client for api registration client

---

bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
pkg/operator/v311_00_assets/bindata.go

The SDN needs some time to converge when endpoints change. This minimal shutdown time delay the actual shutdown (and stop of serving) to avoid that race.

Set minimal-shutdown-duration to 3s

---

pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go

Since https://github.com/openshift/origin/pull/22229 merged, we don't have to reload to get certs.
/hold
holding until I complete testing locally.

use dynamic reloading of certs to avoid rolling out new deployment versions

---

manifests/0000_61_openshift-apiserver-operator_07_deployment.yaml

specifies system-cluster-critical priority for operators that run on masters.
blocks passing smoke tests for ensuring control plane pods always schedule.
see: openshift/origin#22217

manifests: system-cluster-critical priority for operator

---

manifests/0000_61_openshift-apiserver-operator_07_deployment.yaml

for upgrades, we need to have deployment strategy recreate on our operators in case they are ever scaled. We don't want to ever get a lease for new and later get a lease for old.
We need a distinct operator container to make install-gather happy at the moment.
@openshift/sig-master

update deployment for upgrade and install-gather

---

bindata/v3.11.0/openshift-apiserver/ns.yaml
manifests/0000_61_openshift-apiserver-operator_00_namespace.yaml
pkg/operator/v311_00_assets/bindata.go

**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …

Add node-selector annotation to namespace

---

manifests/0000_30_openshift-apiserver-operator_07_deployment.yaml

We don't need this flag, the loglevel controller manage the log level of operator.

manifests: bump loglevel of operator to normal

---

bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
pkg/operator/v311_00_assets/bindata.go

Even the metadata level is not safe as metadata.name is the secret.
Signed-off-by: Monis Khan <mkhan@redhat.com>
@deads2k

Bug 1718052: Do not log OAuth tokens in audit logs

---

pkg/operator/workloadcontroller/apigroup.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go

If the aggregated API check fail emit a warning event with all details we can get from the check.

operator: report more details when api check fail

---

manifests/0000_90_openshift-apiserver-operator_04_servicemonitor-apiserver.yaml

/cc @paulfantom @deads2k @sttts @brancz
/hold
This depends on #207

manifests: add servicemonitor for openshift apiserver

---

pkg/operator/starter.go

Fixes a small typo where a `StaticPodOperatorClient` is created instead of an `OperatorClient`.

use non-static operator client

---

bindata/v3.11.0/openshift-apiserver/ds.yaml
cmd/cluster-openshift-apiserver-operator/main.go
pkg/operator/resourcesynccontroller/resourcesynccontroller.go
pkg/operator/v311_00_assets/bindata.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go

Instead use operator driven rollout. This is enforced by hashing the the configmap contents and adding that to the deployment (that mechanism preexisted).

Bug 1746375: Revert use of watchdog for trusted-ca-bundle

---

Makefile

This PR fixes `make images`, it requires `image name` now. 
(`make images` is only used in local development, AFAIK)

fix make images

---

manifests/0000_30_openshift-apiserver-operator_03_trusted_ca_cm.yaml
pkg/operator/resourcesynccontroller/resourcesynccontroller.go
pkg/operator/v311_00_assets/bindata.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go

The trusted-ca-bundle was never created in the operator NS where
we were trying to sync it from. Have it be created by the CVO in
the operator NS and sync only its data (therefore not the injection
label) to the operand's NS.

Bug 1747260: Fix trusted-ca-bundle CM syncing

---

Dockerfile.rhel7
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go

Can't have source CM UID in metadata when updating the image CM
-----
Tested manually

Bug 1747260: Last (?) fix to trusted-ca CM syncing

---

bindata/v3.11.0/openshift-apiserver/ds.yaml
pkg/operator/v311_00_assets/bindata.go

CRI-O 1.16 made a change to how selinux labels were handled that increased security. In doing so, pod specs need to enable selinuxRelabel. In the case of this initContainer, it is trying to edit the permissions of a file on the host system, which is a security flaw, and thus selinux is denying it.
Add the type spc_t, which allows the container to modify the host file
Signed-off-by: Peter Hunt <pehunt@redhat.com>

add correct label to ds config initContainer

---

pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go

I have come up with this change after having some discussion around the Bugzilla with @stlaz.

Bug 1767156: Fix "Multipleavailable" reason in the code 

---

bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
pkg/operator/v311_00_assets/bindata.go

In order to be able to match a user from IDP with a username which is
normally logged in the audit logs, we need to have the creation of the
Identity API resource logged.
This patch changes the hardcoded auditConfig to log "witethe "identities"
resource of the "user.openshift.io" group at the RequestResponse level.

auditConfig: Log write operations of Identities with RequestResponse

---

README.md

Makes this README look like the kube apiserver operator one.
@openshift/sig-networking owns us documentation about ingresses.

update README to provide more info about operator

---

manifests/0000_90_openshift-apiserver-operator_03_servicemonitor.yaml
pkg/version/version.go

* First commit will make scraping of operator metrics secure
* Second commit will restore collection of operator version metrics
/cc @sttts

Fix metrics

---

manifests/0000_90_openshift-apiserver-operator_04_servicemonitor-apiserver.yaml

These are deployed by monitoring operator, but shouldn't: https://github.com/openshift/cluster-monitoring-operator/blob/e515ed03618466b6a1b9d2fcf12192191bfd90f8/assets/prometheus-k8s/role-specific-namespaces.yaml#L51-L66

Bug 1735509: monitoring: move service monitor RBAC rules to manifests/

---

manifests/0000_30_openshift-apiserver-operator_07_deployment.yaml
manifests/0000_30_openshift-apiserver-operator_08_clusteroperator.yaml

Enables the CVO to exclude manifests in an externally hosted control plane deployment
See https://github.com/openshift/cluster-version-operator/pull/252

Add manifest annotations for hosted deployment exclusions

---

bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
bindata/v3.11.0/openshift-apiserver/ds.yaml
pkg/cmd/resourcegraph/resourcegraph.go
pkg/operator/resourcesynccontroller/resourcesynccontroller.go
pkg/operator/v311_00_assets/bindata.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go

Remove configuration for the side-channel cluster-authentication and instead use the "standard" upstream, zero-config option.

use upstream cluster authentication config

---

bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
pkg/operator/v311_00_assets/bindata.go

The latter is the official flag name, the former from our carry patch.

Replace --{minimal-shutdown -> shutdown-delay}-duration

---

pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go

Introduced through https://github.com/openshift/cluster-openshift-apiserver-operator/pull/248

Bug 1781574: Fix panic in workload controller

---

pkg/operator/nsfinalizercontroller/finalizer_controller.go
pkg/operator/starter.go

All aggregated APIs face a finalization problem.  This will allow us to re-use the logic in the authentication operator.
/assign @p0lyn0mial @sanchezl @sohankunkerkar

separate finalizer cleanup controller to allow re-use

---

bindata/v3.11.0/openshift-apiserver/ds.yaml
pkg/operator/v311_00_assets/bindata.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go

This makes the verbosity easy for workloads to add in their operator manifest.

replace verbosity based on string substitution for ease

---

pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go

Use the standard apply methods to gain proper eventing, caching, and diff computation.
/assign @stlaz @adambkaplan 
@stlaz @sttts @adambkaplan need a bug written for the direct dependency on the image-registry namespace above.  It should never have merged that way.  Communication between components happens through openshift-config-manged so we can see who is accessing what and avoid trip deployment deps.

vastly simplify the image registry trust configmap

---

pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go

This allows us to avoid requiring the same loops manage daemonsets and the resources they depend upon.  It also cleans up an SA dependency that wasn't logically required.
/assign @stlaz

switch to including hashes in annotation instead of ordered plumbing

---

bindata/v3.11.0/openshift-apiserver/defaultconfig.yaml
pkg/operator/v311_00_assets/bindata.go

If you say `net.Listen("tcp", "0.0.0.0:8443")`, golang will actually create a dual-stack IPv4/IPv6 listening socket. But for historical reasons (having to do with bad IPv6 compat in older kube I think), we default to passing `"tcp4"` (the default value of `configv1.ServingInfo.BindNetwork`) instead of `"tcp"`, forcing IPv4-only.
There is no reason these days for servers on the pod network to enforce IPv4-only, so this overrides the default for openshift-apiserver.
This will need to be backported to 4.3.
cc @russellb

Specify "bindNetwork: tcp" so apiserver will work on IPv6 single-stack

---

pkg/operator/apiservercontrollerset/apiservercontrollerset.go
pkg/operator/apiservicecontroller/apiservice_controller.go
pkg/operator/starter.go

This is a crude stab at trying to separate and generalize setting up our own API servers.
/assign @deads2k

split apiserver controllers initialization to a separate module

---

manifests/0000_30_openshift-apiserver-operator_08_clusteroperator.yaml
pkg/operator/starter.go
pkg/operator/workloadcontroller/workload_controller.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
vendor/modules.txt

builds on #301 
The last commit is unique and sets the operand to the same version as the operator when it has achieved its consistent level.
/assign @mfojtik

bug 1792386: set the operand version and make the CVO wait

---

pkg/operator/starter.go
pkg/operator/workloadcontroller/workload_controller.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
vendor/modules.txt

@soltysh @sanchezl @sttts @p0lyn0mial @stlaz 
This is a fairly comprehensive rewrite of condition handling in the openshift-apiserver to give us discrete conditions to union.  This makes it clear (at least to me) that we have different logical control loops at play and need to decide what to do.  I have opinions (naturally).

bug 1792382: large scale condition rewrites

---

manifests/0000_90_openshift-apiserver-operator_04_servicemonitor-apiserver.yaml

Add a new label 'apiserver' to apiserver_current_inflight_requests
metric to identify that the source is openshift apiserver.
The label would say - apiserver:openshift-apiserver
Do the similar for kube-apiserver - apiserver:kube-apiserver

Bug 1798215: Add a new label 'apiserver' to identify the source

---

manifests/0000_90_openshift-apiserver-operator_04_servicemonitor-apiserver.yaml

This shouldn't have any effect on our alerts or dashboards as the buckets are cumulative and for those purposes the remaining buckets should be sufficient.
Note: this change was made in "upstream" kube-promethues repo, see background for this coreos/kube-prometheus#387
Same as https://github.com/openshift/cluster-kube-apiserver-operator/pull/752

Bug 1801154: manifests/: Throw away unused high cardinality apiserver duration buckets

---

pkg/operator/configobservation/etcdobserver/observe_etcd.go
pkg/operator/configobservation/etcdobserver/observe_etcd_test.go
pkg/operator/operatorclient/interfaces.go
pkg/operator/starter.go

oas should never use the bootstrap etcd member.
Switch to the new `host-etcd-2`, which never contains the etcd bootstrap member, endpoints resource to determine the storage urls.

Bug 1806671: openshift-apiserver should never use the bootstrap etcd member

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
pkg/operator/apiservicecontroller/apiservice_controller_test.go
pkg/operator/deploynodeprovider.go
pkg/operator/nsfinalizercontroller/finalizer_controller.go
pkg/operator/starter.go
pkg/operator/v311_00_assets/bindata.go
pkg/operator/workloadcontroller/workload_controller.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
test/e2e/operator_test.go

The switch from using a daemonset to using a deployment is intended to improve reliability during upgrade.
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1804717
/cc @sttts @deads2k

bug 1804717: Switch to managing openshift-apiserver pods with a deployment

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
pkg/operator/apiservicecontroller/apiservice_controller.go
pkg/operator/deploynodeprovider.go
pkg/operator/prunecontroller/prune_controller.go
pkg/operator/starter.go
pkg/operator/v311_00_assets/bindata.go
pkg/operator/workloadcontroller/workload_controller.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go

This PR addresses comments and otherwise unresolved issues from #313 
- Sets the replica count according to the number of master nodes
- Ensures the operator doesn't report degraded if the number of available nodes exceeds the desired replica count (a likely scenario during rollout)
- Removes the unintentionally applied `previousGeneration` label from the deployment
- Updates previously unnoticed daemonset-derived variable names.
cc: @deads2k @sttts @tnozicka

bug 1804717: Cleanup switch to managing openshift-apiserver pods with a deployment

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
pkg/operator/apiservicecontroller/apiservice_controller.go
pkg/operator/apiservicecontroller/apiservice_controller_test.go
pkg/operator/deploynodeprovider.go
pkg/operator/nsfinalizercontroller/finalizer_controller.go
pkg/operator/prunecontroller/prune_controller.go
pkg/operator/starter.go
pkg/operator/v311_00_assets/bindata.go
pkg/operator/workloadcontroller/workload_controller.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00_test.go
test/e2e/operator_test.go

Cherry-picks #313 and #324 to release-4.4.

Bug 1805872: 4.4 cherry-pick of switch from daemonset to deployment

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
pkg/operator/v311_00_assets/bindata.go
pkg/operator/workloadcontroller/workload_controller_openshiftapiserver_v311_00.go

Update the deployment rollout strategy to never allow more than one pod to run at a time on a given master node. This change removes the need to set an anti-affinity uuid label since the previous replica set's pod must be turned down before a new one can be scheduled.
The previous rollout strategy allowed more than one pod per node to run on a given master node during rollout. This was a break from the rollout strategy used by the daemonset controller, where each node had its pod turned down before another could start. The daemonset behavior must be maintained to ensure coherent audit logs.

Bug 1808568: Fix rollout strategy to never run more than one pod per node

---

pkg/operator/configobservation/etcdobserver/observe_etcd.go

DeepEqual fails on type comparison resulting in spamming update events

Bug 1814618: storage urls observer: prevent event/log spam

---

pkg/operator/configobservation/etcdobserver/observe_etcd.go

DeepEqual fails on type comparison resulting in spamming update events

Bug 1814621: storage urls observer: prevent event/log spam

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
pkg/operator/v311_00_assets/bindata.go

The openshift-apiserver uses approximately 10% of master CPU in a
reasonable medium sized workload. Given a 1 core per master baseline
(since CPU is compressible and shared), assign the openshift-apiserver
roughly 10% of that core on each master.
4.4 bug is 1812709

Bug 1812583: Normalize CPU requests on masters

---

pkg/operator/starter.go

Fix: `W0318 12:57:21.574726       1 builder.go:88] graceful termination failed, controllers failed with error: stopped`

starter: fix graceful operator shutdown

---

pkg/operator/oauthapiencryptioncontroller/oauthapiencryptioncontroller.go
pkg/operator/oauthapiencryptioncontroller/oauthapiencryptioncontroller_test.go

this PR adds `OAuthAPIServerController` that will manage `encryption-config-openshift-oauth-apiserver` as described in https://github.com/openshift/enhancements/blob/master/enhancements/etcd/etcd-encryption-for-separate-oauth-apis.md

OAuthAPIServerController

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
pkg/operator/v311_00_assets/bindata.go

OpenShift API Server needs to make use of node pull credentials during `image stream import`. This PR mounts them inside the operand pods. For further details please refer to the [enhancement proposal](https://github.com/openshift/enhancements/pull/136).
Note: Please review https://github.com/openshift/openshift-apiserver/pull/83 as well

DEVEXP-424: Mounting node pull secrets

---

pkg/operator/starter.go

`migrationInformer.Start(ctx.Done())` is repeated twice and one instance of it can be removed

Bug 1828835: remove duplicate migration informer start

---

pkg/operator/workload/workload_openshiftapiserver_v311_00_sync.go

The new method hashes the spec of the deployment which removes the setting an annotation containing the replica count.
/cc @deads2k @stlaz

Bug 1827050: Update to use revised ApplyDeployment

---

pkg/operator/starter.go

This will cause insights operator to capture events from etcd operator namespace in case openshift apiserver operator is degraded.

Bug 1832220: operator: add openshift-etcd-operator namespace to related objects

---

pkg/operator/starter.go
pkg/operator/workload/workload_openshiftapiserver_v311_00_sync.go

reverts waiting for `requestheader-client-ca-file` in `extension-apiserver-authentication` before rolling out a new version.
it is replaced by https://github.com/openshift/kubernetes-apiserver/pull/10 which essentially shifts the logic to API Servers. From now on a server watches and reacts to changes in the config map in real-time.

Bug 1795163: openshift-apiserver operator not available when used for single node cluster (CRC) 

---

pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
pkg/operator/configobservation/etcdendpoints/OWNERS
pkg/operator/configobservation/etcdendpoints/observe_etcd_endpoints.go
pkg/operator/configobservation/etcdendpoints/observe_etcd_endpoints_test.go
pkg/operator/configobservation/etcdobserver/OWNERS
pkg/operator/configobservation/interfaces.go

xref https://github.com/openshift/cluster-etcd-operator/pull/354

Bug 1836927: Prefer etcd endpoints configmap for storage URL discovery

---

pkg/operator/starter.go
pkg/operator/workloadcontroller/workload_controller.go

reverts waiting for `requestheader-client-ca-file` in `extension-apiserver-authentication` before rolling out a new version.
it is replaced by https://github.com/openshift/openshift-apiserver/pull/103 which essentially shifts the logic to API Servers. From now on a server watches and reacts to changes in the config map in real-time.

Bug 1840857: openshift-apiserver doesn't live reload extension-apiserver-authentication trust

---

pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go

this makes the e2e test easier to write.

tweak connectivity check names to avoid overlap

---

pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
pkg/operator/connectivitycheckcontroller/connectivity_check_template.go
pkg/operator/starter.go

* name some endpoints using node names to exploit dynamic check updates
* add checks for load balancers
* refactor to make it easier to use conectivitycheckcontroller from library-go in the future.

connectivitycheckcontroller: sync w/ kube-apiserver improvements

---

pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go

avoid overlaping connectivity check names

---

go.mod
go.sum
pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
pkg/operator/starter.go
vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/audit_policies.go
vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_template.go
vendor/modules.txt

- connectivitycheckcontroller: fix dynamic check updates
- bump(*)
- react to bump(*)
- connectivitycheckcontroller: use generic check controller

connectivitycheckcontroller: use generic controller

---

Dockerfile.rhel7

To unblock https://github.com/openshift/cluster-openshift-apiserver-operator/pull/381
/assign @tnozicka

Bug 1871890: Bump coao to golang 1.14 to match kube

---

pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
test/e2e/connectivity_check_test.go

PodNetworkConnectivityCheck resources were not being created.
Add e2e-test to prevent this issue in the future.

Bug 1870922: oc get PodNetworkConnectivityCheck -n openshift-apiserver has no resource

---

manifests/0000_30_openshift-apiserver-operator_09_flowschema.yaml

- `SAR` or `tokenreviews` from oas 
- Any other requests from oas server.
- Traffic from oas operator.
See https://github.com/openshift/cluster-kube-apiserver-operator/pull/966 for more details.

flowschema for openshift apiserver and its operator

---

Dockerfile

Updating ose-cluster-openshift-apiserver-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-cluster-openshift-apiserver-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating ose-cluster-openshift-apiserver-operator builder & base images to be consistent with ART

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissions.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
vendor/modules.txt

Pickup https://github.com/openshift/library-go/pull/918.
Works with https://github.com/openshift/cluster-kube-apiserver-operator/pull/978.

Bug 1876166: need to be able to disable kube-apiserver connectivity checks

---

pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
test/e2e/connectivity_check_test.go

Turning off again as it is preventing 4.6.0 -> 4.7 from completing successfully.

connectivitycheckcontroller: disable by default

---

manifests/0000_90_openshift-apiserver-operator_04_servicemonitor-apiserver.yaml

openshift-apiserver has a histogram `etcd_request_duration_seconds` that measures latency between the kube-apiserver and etcd instance. This metrics is currently dropped by cluster-prometheus. Enable this metrics in OpenShift so we have visibility into etcd latency.
We ensured that this does not enable other unwanted metrcis
> count by(__name__) ({__name__=~"etcd_request.+"})
etcd_request_duration_seconds_bucket
etcd_request_duration_seconds_count
etcd_request_duration_seconds_sum
Related PR: https://github.com/openshift/cluster-kube-apiserver-operator/pull/897

enable etcd latency metric

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
pkg/operator/v311_00_assets/bindata.go

While the current log directory permissions are restrictive and correct,
the file permissions are too permissive and it raises flags on
evaluations of the deployment. Let's instead change the permissions to
0600 which is more appropriate for these types of logs.
Note that while this is a superficial fix, it is also meant to address upgrades
(on an upgrade scenario, the permissions of old and rotated log files will be
fixed).

Restrict log permissions

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
pkg/operator/v311_00_assets/bindata.go

This uses a more restrictive file mode for the mounted secrets for the
openshift-apiserver container. By the default, the resulting mode of the
files will be 0644, which is not ideal. So let's use 0600 which ensures
that the files are only accessible by root.

Use more restrictive defaultMode for secret mounts

---

Makefile
go.mod
go.sum
test/e2e/operator_test.go
vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
vendor/github.com/openshift/library-go/test/library/apiserver/apiserver.go
vendor/modules.txt

especially that we also run the encryption tests which require a few rollout and migration time.

improve e2e tests

---

bindata/v3.11.0/openshift-apiserver/ns.yaml
pkg/operator/v311_00_assets/bindata.go

The apiserver DS runs with privileged SCC anyway.

Bug 1806918: remove run-level=1 from openshift-apiserver NS

---

manifests/0000_30_openshift-apiserver-operator_00_namespace.yaml
manifests/0000_30_openshift-apiserver-operator_01_operator.cr.yaml
manifests/0000_30_openshift-apiserver-operator_03_configmap.yaml
manifests/0000_30_openshift-apiserver-operator_03_trusted_ca_cm.yaml
manifests/0000_30_openshift-apiserver-operator_04_roles.yaml
manifests/0000_30_openshift-apiserver-operator_05_serviceaccount.yaml
manifests/0000_30_openshift-apiserver-operator_06_service.yaml
manifests/0000_30_openshift-apiserver-operator_07_deployment.yaml
manifests/0000_30_openshift-apiserver-operator_08_clusteroperator.yaml
manifests/0000_30_openshift-apiserver-operator_09_flowschema.yaml
manifests/0000_90_openshift-apiserver-operator_01_prometheusrole.yaml
manifests/0000_90_openshift-apiserver-operator_02_prometheusrolebinding.yaml
manifests/0000_90_openshift-apiserver-operator_03_servicemonitor.yaml
manifests/0000_90_openshift-apiserver-operator_04_servicemonitor-apiserver.yaml
manifests/0000_90_openshift-apiserver-operator_05_check-endpoints_service.yaml
manifests/0000_90_openshift-apiserver-operator_05_check-endpoints_servicemonitor.yaml

This partially implements phase 1 of https://github.com/openshift/enhancements#482
and does not change behavior. Initially, all cluster-openshift-apiserver-operator
manifests are included in the single-node-developer cluster profile.
Follow-on PRs may exclude any of these that are not needed in the
profile.

Bug 1915473: Annotate manifests for single-node-developer cluster profile

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
pkg/operator/v311_00_assets/bindata.go

Control plane containers should have requests set for cpu and memory.

Bug 1905298: openshift-apiserver initContainer fix-audit-permissions is not requesting required resources: cpu, memory 

---

manifests/0000_30_openshift-apiserver-operator_09_flowschema.yaml

Important Note: We support upgrade and downgrade - 4.7 to 4.6 downgrade would behave very badly (in a skew case). So we should NOT back port to 4.7

switch to v1beta1 for the p&f APIs

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
pkg/operator/v311_00_assets/bindata.go

the pod name and the namespace are used by the termination code to properly record events.
before the change the termination events were recorded to the default namespace and weren't associated with any pod.
after the change, the termination evens are recorded in the openshift-apiserver namespace and are bound to oas pods.

expose pod information to oas container via env variables

---

bindata/v3.11.0/config/defaultconfig.yaml
pkg/operator/v311_00_assets/bindata.go

The general rule of thumb is to wait ~5s-10s for any service behind the service network.
During that time the controllers should remove the endpoint from the pool and the application won't receive any new connections.
xref: https://github.com/openshift/openshift-apiserver/pull/198

extends shutdown delay duration to 10 seconds

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
pkg/operator/v311_00_assets/bindata.go

Bug 1942725: explicitly allow apiserver pods to write to their root FS

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
bindata/v3.11.0/openshift-apiserver/ns.yaml
manifests/0000_30_openshift-apiserver-operator_00_namespace.yaml
manifests/0000_30_openshift-apiserver-operator_07_deployment.yaml
pkg/operator/v311_00_assets/bindata.go

In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.

Add management workload annotations

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
manifests/0000_30_openshift-apiserver-operator_07_deployment.yaml
pkg/operator/v311_00_assets/bindata.go

As per https://github.com/openshift/enhancements/pull/739, the workload
annotations names are changing.
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
/hold
Hold until after https://github.com/openshift/kubernetes/pull/632 is merged please

Rename workload annotations

---

Makefile
test/e2e-encryption-rotation/e2e-encryption-rotation_test.go

We are going to move the rotation tests to a separate CI job. It will shorten the overall time needed to test encryption but also increase the pass rate of the tests as we have seen them frequently failing due to a timeout.
This PR adds only a stub so that the new CI job can be configured.
We have already split the tests for kas-o in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1131

Bug 1943804: stub for splitting encryption tests

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/preconditions.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
vendor/modules.txt

Before this change, the precondition checker could run the encryption controllers when the caches haven't been synchronized.
During synchronization, the controllers send live requests to the API server.
A **single** failed request can put a controller into a degraded state and leave it in that state forever. 
Thus the precondition function MUST be called after the caches were synchronized. This PR ensures that.
For example, in [this](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.8-e2e-aws-upgrade/1400652395809083392/artifacts/e2e-aws-upgrade/) CI run the `kas-o` operator acquired a lock at `03:33:24`:
at `03:33:40` the `EncryptionPruneControllerDegraded` went degraded and **never** recovered.
around the same time, a …

Bug 1969631: encryption controllers wait for all informers before running the sync loops

---

manifests/0000_90_openshift-apiserver-operator_03_servicemonitor.yaml
manifests/0000_90_openshift-apiserver-operator_04_servicemonitor-apiserver.yaml
manifests/0000_90_openshift-apiserver-operator_05_check-endpoints_servicemonitor.yaml

The CMO is now capable of using client cert auth to scrape the metrics endpoints. Use that in our components to reduce API load and allow metrics collection when the API is down - given further authz conditions are met.

Bug 1986829: metrics: use client cert auth for metrics scraping

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
pkg/operator/v311_00_assets/bindata.go

openshift-apiserver needs to run as root in order to be able to write audit to /var/log/openshift-apiserver.
Currently only "priviledged: true" is specified which can lead to picking SCCs that do not have the RunAsAny policy.
This fixes it by specifying runAsUser: 0 explicitly.
/cc @stlaz @sttts

Bug 1960680: bindata: run openshift-apiserver as root explicitly.

---

bindata/v3.11.0/openshift-apiserver/pdb.yaml
pkg/operator/starter.go
pkg/operator/v311_00_assets/bindata.go

In case master nodes are drained to quickly in a row there's no
waiting until instances go back to available. So it's possible
for two or more replicas to go unavailable which may lead
to all instances going unavailable.
Based on https://github.com/openshift/library-go/pull/1056/commits/8efd1883d406cc389eb25e2a257c4451dfbd668c

bug 1998031: Deploy PDB to prevent more than one replica going unavailable

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
pkg/operator/v311_00_assets/bindata.go

This is a manual cherry-pick of #465

[release-4.6] Bug 1996051: bindata: run openshift-apiserver as root explicitly.

---

bindata/v3.11.0/openshift-apiserver/ns.yaml
pkg/operator/v311_00_assets/bindata.go

Starting with OpenShift 4.10 we are introducing PodSecurity admission (https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement).
Currently, all pods are marked as privileged, however, over time we want to enforce at least baseline, admirably restricted as default. In order not to break control plane workloads this allows workloads in `openshift-apiserver` namespace to run privileged pods.
See https://github.com/openshift/enhancements/pull/899 for more details (and excuse the eventual consistency of updates).
/cc @stlaz

podsecurity: enforce privileged for openshift-apiserver namespace

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/apiserver/controller/apiservice/apiservice_controller.go
vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
vendor/modules.txt

clean pick of https://github.com/openshift/library-go/pull/1210
Fixes the following issue:
When an operator is shutting down the `apiservice-controller` might fail on checking the availability of the downstream servers due to the context being closed. The condition (Available) will manifest in the operator's status. This PR simply avoids updating the condition when the process is shutting down.
1.  If the Bugzilla associated with the PR has the "FastFix" keyword, the subjective assessment on the issue has already been done and a customer is impacted. These PRs should be prioritized for merge.
2. The bug has significant impact either through severity, reduction in supportability, or number of users affected.
3. For branches that are in the Maintenance lifecycle phase:
4. The severity field …

Bug 1994655: apiservice-controller: don't update the failing condition when an operator has been requested to shutdown

---

bindata/v3.11.0/openshift-apiserver/pdb.yaml
pkg/operator/starter.go
pkg/operator/v311_00_assets/bindata.go

In case master nodes are drained to quickly in a row there's no
waiting until instances go back to available. So it's possible
for two or more replicas to go unavailable which may lead
to all instances going unavailable.
Backporting https://github.com/openshift/cluster-openshift-apiserver-operator/pull/472

bug 2003946: Deploy PDB to prevent more than one replica going unavailable

---

go.mod
go.sum
pkg/operator/starter.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/bindata/bindata.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
vendor/modules.txt

Builds on top of https://github.com/openshift/library-go/pull/1246 and WithIsSNOCheck from https://github.com/openshift/library-go/pull/1238.

bug 2039670: Create the PDB dynamically so it does not get created on the SNO topology

---

bindata/v3.11.0/config/defaultconfig.yaml
bindata/v3.11.0/openshift-apiserver/deploy.yaml
pkg/operator/v311_00_assets/bindata.go

This also uses a startup probe instead of a long initial delay seconds for livez and instead of excessive failure thresholds for readiness.
/assign @tkashem

Bug 2066886: make apiserver readiness probe honor readyz

---

manifests/00_namespace.yaml

We dropped the run-level label from this namespace back in 4.5
but because of how the cluster-version operator reconciles manifest
labels, dropping a label from the manifest does not remove it from the
in-cluster resource when old clusters are updated into the new
manifest.  This commit uses the approach the cluster-version
operator used to drop its run-level, by setting the value to an
empty string, which the run-level-consuming code treats identically to
an unset label.
This avoids errors about:
...container has runAsNonRoot and image will run as root...
when updating to 4.11 in case the operator deployment  manifest specifically
requests runAsNonRoot: true.

Bug 2101880: operator NS manifest: Set empty openshift.io/run-level

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
vendor/modules.txt

OCPBUGS-5345: routes/status resources can leak sensitive data, exclude it from audit

---

Makefile
go.mod
go.sum
test/e2e-encryption-rotation/e2e-encryption-rotation_test.go
test/e2e-encryption/encryption_test.go
vendor/github.com/openshift/build-machinery-go/make/targets/golang/test-unit.mk
vendor/modules.txt

This PR brings the changes from https://github.com/openshift/cluster-kube-apiserver-operator/pull/1449 over to cluster-authentication-operator.
Separately new jobs are being added in https://github.com/openshift/release/pull/40119 in order to run the new AES-GCM encryption tests.

Add AES-GCM encryption tests

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
pkg/operator/v311_00_assets/bindata.go

This sets the required-scc annotation for openshift-apiserver to `privileged` as openshift-apiserver is a privileged pod.
/cc @deads2k @stlaz

AUTH-408: bindata: set required-scc

---

manifests/0000_90_openshift-apiserver-operator_04_servicemonitor-apiserver.yaml

Remove "include.release.openshift.io/ibm-cloud-managed:" annotation annotation to CVO not to deploy the service monitor

OCPBUGS-18115: Remove "include.release.openshift.io/ibm-cloud-managed:" annotation

---

bindata/v3.11.0/openshift-apiserver/pdb.yaml
pkg/operator/v311_00_assets/bindata.go

allow eviction of unhealthy (not ready) pods even if there are no disruptions allowed on a PodDisruptionBudget. This can help to drain/maintain a node and recover without a manual intervention when multiple instances of nodes or pods are misbehaving. Use this with caution, as this option can disrupt perspective pods that have not yet had a chance to become healthy.

WRKLDS-1004: use AlwaysAllow UnhealthyPodEvictionPolicy in PDBs

---

manifests/0000_90_openshift-apiserver-operator_04_servicemonitor-apiserver.yaml

The apiserver_request_sli_duration_seconds metric was introduced as a
replacement of apiserver_request_slo_duration_seconds which is
deprecated in Kubernetes 1.27.
To also avoid storing duplicated data in Prometheus, we need to drop
the apiserver_request_slo_duration_seconds at the ServiceMonitor level.

OCPBUGS-18939: manifest: drop slo latency metrics in favor of sli

---

Makefile

before this change the following targets didn't work:
- make test-e2e-encryption-rotation-aescbc
- make test-e2e-encryption-rotation-aesgcm
as a result corresponding CI jobs failed. For example:
- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-openshift-apiserver-operator/575/pull-ci-openshift-cluster-openshift-apiserver-operator-master-e2e-gcp-operator-encryption-rotation-aesgcm/1779820017387311104
- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-openshift-apiserver-operator/575/pull-ci-openshift-cluster-openshift-apiserver-operator-master-e2e-gcp-operator-encryption-rotation-aescbc/1779820014874923008
This PR fixes the issue by adding "-" prefix to the targets.

NO-ISSUE: Makefile: fixes test-e2e-encryption-rotation targets

---

manifests/07_deployment.yaml

[OCPBUGS-36150](https://issues.redhat.com/browse/OCPBUGS-36150)
Manual cherry-pick of #573

[release-4.15] OCPBUGS-36150: Set required-scc for openshift workloads

---

pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
pkg/operator/configobservation/images/observe_images.go
pkg/operator/configobservation/images/observe_images_test.go

As per https://github.com/openshift/enhancements/pull/1605, there was a
new field introduced in the image config spec and status which reflects
the global value to be set for imagestream import mode which is behind a
featuregate. This PR reads the image config status, checks if the importmode
string is present and syncs that value in the imagepolicyconfig of the
observed config to be used by the apiserver.
API changes: https://github.com/openshift/api/pull/1928
openshift-apiserver changes: https://github.com/openshift/openshift-apiserver/pull/443
image-registry-operator changes: https://github.com/openshift/cluster-image-registry-operator/pull/1090

MULTIARCH-4557: Sync import mode image config status field in the observed config

---

bindata/v3.11.0/openshift-apiserver/deploy.yaml
pkg/operator/v311_00_assets/bindata.go

Explicitly exclude etcd and etcd-readiness checks (OCPBUGS-48177) and have etcd operator take responsibility for properly reporting etcd readiness. Justification: kube-apiserver instances get removed from a load balancer when etcd starts to report not ready (as will KA's /readyz). Client connections can withstand etcd unreadiness longer than the readiness timeout is. Thus, it is not necessary to drop connections in case etcd resumes its readiness before a client connection times out naturally.
Follow up for https://github.com/openshift/kubernetes/pull/2174

OCPBUGS-48177: Exclude etcd readiness checks from /readyz to ignore temporary etcd hiccups
